name: GuessTheNumber
version: 3.0.0
api: [3.0.0-ALPHA7]
author: SalmonDE
main: SalmonDE\GuessTheNumber\Number
description: Chat games about simple maths and guessing
permissions:
    guessthenumber:
        description: Main permission node
        children:
            guessthenumber.play:
                children:
                    guessthenumber.play.randomint:
                        description: Permission to take part in a random integer game
                        default: true
                    guessthenumber.play.square:
                        description: Permission to take part in a square game
                        default: true
                    guessthenumber.play.addition:
                        description: Permission to take part in a addition game
                        default: true
                    guessthenumber.play.minus:
                        description: Permission to take part in a subtraction game
                        default: true
                    guessthenumber.play.multiplication:
                        description: Permission to take part in a multiplication game
                        default: true
                    guessthenumber.play.division:
                        description: Permission to take part in a division game
                        default: true
                    guessthenumber.play.factorial:
                        description: Permission to take part in a factorial game
                        default: true
            guessthenumber.cmd:
                children:
                    guessthenumber.cmd.randomint:
                        description: Permission to start a random integer game
                    guessthenumber.cmd.square:
                        description: Permission to start a square game
                    guessthenumber.cmd.addition:
                        description: Permission to start an addition game
                    guessthenumber.cmd.subtraction:
                        description: Permission to start a subtraction game
                    guessthenumber.cmd.multiplication:
                        description: Permission to start a multiplication game
                    guessthenumber.cmd.division:
                        description: Permission to start a division game
                    guessthenumber.cmd.factorial:
                        description: Permission to start a factorial game
                    guessthenumber.cmd.solution:
                        description: Permission to get the solution of the current game
                    guessthenumber.cmd.abort:
                        description: Permission to abort the current game
